'use client'

import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { BarChart3, Download, FileText, Link2, Mail, Mic, RefreshCw, Square, Trash2 } from 'lucide-react'
import { useToast } from '@/components/ui/Toast'

const platforms = [{ value: 'meta_ads', label: 'Meta Ads', colour: '#1877F2' },{ value: 'instagram', label: 'Instagram', colour: '#C13584' },{ value: 'google_ads', label: 'Google Ads', colour: '#4285F4' }]
const date = (d: Date) => d.toISOString().slice(0,10), number = (n=0) => Number(n).toLocaleString(undefined,{maximumFractionDigits:1}), money=(n=0)=>`AED ${Number(n).toLocaleString(undefined,{maximumFractionDigits:2})}`, pct=(n=0)=>`${Number(n).toFixed(2)}%`
const periods: Record<string,()=>[string,string]> = {
  '7':()=>{const e=new Date(),s=new Date();s.setDate(e.getDate()-6);return[date(s),date(e)]},
  '30':()=>{const e=new Date(),s=new Date();s.setDate(e.getDate()-29);return[date(s),date(e)]},
  '90':()=>{const e=new Date(),s=new Date();s.setDate(e.getDate()-89);return[date(s),date(e)]},
  month:()=>{const e=new Date(),s=new Date(e.getFullYear(),e.getMonth(),1);return[date(s),date(e)]},
  previous:()=>{const e=new Date();e.setDate(0);const s=new Date(e.getFullYear(),e.getMonth(),1);return[date(s),date(e)]},
}

function Trend({days}:{days:any[]}){const max=Math.max(1,...days.map(d=>d.spend));return <div className="h-48 flex items-end gap-1 pt-5">{days.map(d=><div key={d.date} className="flex-1 min-w-[3px] group relative bg-brand-100 rounded-t" style={{height:`${Math.max(2,d.spend/max*100)}%`}}><div className="hidden group-hover:block absolute z-10 bottom-full mb-2 left-1/2 -translate-x-1/2 bg-ink text-white text-xs rounded p-2 whitespace-nowrap">{d.date}<br/>{money(d.spend)} · {number(d.clicks)} clicks</div></div>)}</div>}
function Delta({value}:{value?:number|null}){return value==null?null:<span className={`text-xs ${value>=0?'text-green-700':'text-red-600'}`}>{value>=0?'+':''}{value.toFixed(1)}% vs prior</span>}

export default function CampaignReportingPage(){
 const toast=useToast(), initial=periods['30']()
 const [clients,setClients]=useState<any[]>([]),[projects,setProjects]=useState<any[]>([]),[connections,setConnections]=useState<any[]>([])
 const [client,setClient]=useState(''),[project,setProject]=useState(''),[preset,setPreset]=useState('30'),[start,setStart]=useState(initial[0]),[end,setEnd]=useState(initial[1]),[timezone,setTimezone]=useState('Asia/Dubai'),[provider,setProvider]=useState(''),[campaign,setCampaign]=useState(''),[tab,setTab]=useState('overview'),[data,setData]=useState<any>(null)
 const [loading,setLoading]=useState(false),[canManage,setCanManage]=useState(false),[commentary,setCommentary]=useState(''),[recipient,setRecipient]=useState(''),[generating,setGenerating]=useState(false),[recording,setRecording]=useState(false),[audio,setAudio]=useState<Blob|null>(null)
 const [form,setForm]=useState({provider:'meta_ads',account:'',name:'',manager:''}), recorder=useRef<MediaRecorder|null>(null), chunks=useRef<Blob[]>([])
 useEffect(()=>{Promise.all([fetch('/api/clients').then(r=>r.json()),fetch('/api/projects').then(r=>r.json()),fetch('/api/profiles/me').then(r=>r.json())]).then(([c,p,me])=>{setClients(Array.isArray(c)?c:[]);setProjects(Array.isArray(p)?p:[]);setCanManage(['owner','admin','manager'].includes(me.role));if(c?.[0]){setClient(c[0].id);setRecipient(c[0].email||'')}})},[])
 const loadConnections=useCallback(()=>{if(canManage)fetch('/api/campaign-reporting/connections').then(r=>r.json()).then(d=>setConnections(Array.isArray(d)?d:[]))},[canManage]);useEffect(()=>{loadConnections()},[loadConnections])
 const load=useCallback(async()=>{if(!client)return;setLoading(true);const q=new URLSearchParams({client,start,end,compare:'true'});if(project)q.set('project',project);if(provider)q.set('provider',provider);if(campaign)q.set('campaign',campaign);const r=await fetch(`/api/campaign-reporting/dashboard?${q}`),b=await r.json();setLoading(false);r.ok?setData(b):toast.error(b.error||'Could not load report')},[client,project,start,end,provider,campaign,toast]);useEffect(()=>{load()},[load])
 const clientProjects=useMemo(()=>projects.filter(p=>p.client_id===client),[projects,client]), totals=data?.totals??{}, changes=data?.comparison?.changes??{}
 function setRange(v:string){setPreset(v);if(periods[v]){const [s,e]=periods[v]();setStart(s);setEnd(e)}}
 async function connect(e:React.FormEvent){e.preventDefault();const r=await fetch('/api/campaign-reporting/connections',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider:form.provider,client_id:client,project_id:project||null,external_account_id:form.account,account_name:form.name,login_customer_id:form.manager})}),b=await r.json();if(!r.ok)return toast.error(b.error||'Could not create connection');location.href=`/api/campaign-reporting/oauth/${form.provider}/start?connection=${b.id}`}
 async function sync(id:string){const r=await fetch('/api/campaign-reporting/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({connectionId:id})}),b=await r.json();r.ok?toast.success(`Imported ${b.imported} daily campaign records`):toast.error(b.error);load();loadConnections()}
 async function remove(id:string){if(!confirm('Remove this connection? Historical reporting data will remain.'))return;await fetch(`/api/campaign-reporting/connections/${id}`,{method:'DELETE'});loadConnections()}
 async function startVoice(){try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];recorder.current=new MediaRecorder(stream);recorder.current.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};recorder.current.onstop=()=>{setAudio(new Blob(chunks.current,{type:recorder.current?.mimeType||'audio/webm'}));stream.getTracks().forEach(t=>t.stop())};recorder.current.start();setRecording(true)}catch{toast.error('Microphone permission is required')}}
 function stopVoice(){recorder.current?.stop();setRecording(false)}
 async function report(send=false){setGenerating(true);const fd=new FormData();Object.entries({clientId:client,projectId:project,start,end,timezone,provider,campaign,commentary,recipient,send:String(send)}).forEach(([k,v])=>fd.set(k,v));if(audio)fd.set('audio',audio,'voice-note.webm');const r=await fetch('/api/campaign-reporting/reports',{method:'POST',body:fd});if(!r.ok){const b=await r.json();setGenerating(false);return toast.error(b.error||'Could not generate report')}const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`Campaign-Report-${start}-to-${end}.pdf`;a.click();URL.revokeObjectURL(url);setGenerating(false);toast.success(send?'Report emailed and downloaded':'Report saved and downloaded')}
 const metrics=[['Spend',money(totals.spend),'spend'],['Impressions',number(totals.impressions),'impressions'],['Clicks',number(totals.clicks),'clicks'],['CTR',pct(totals.ctr),'ctr'],['Conversions',number(totals.conversions),'conversions'],['Cost / result',money(totals.cpa),'cpa'],['CPC',money(totals.cpc),'cpc'],['ROAS',`${Number(totals.roas||0).toFixed(2)}×`,'roas']]
 return <div className="space-y-6">
  <div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-semibold text-ink flex items-center gap-2"><BarChart3 className="w-6 h-6 text-brand-600"/>Campaign Report Studio</h1><p className="text-sm text-taupe-500 mt-1">Analyse, explain, package, and send complete client performance reports.</p></div><div className="flex gap-2"><button className="btn-secondary flex items-center gap-2" disabled={generating||!client} onClick={()=>report(false)}><Download className="w-4 h-4"/>PDF</button><button className="btn-primary flex items-center gap-2" disabled={generating||!client||!recipient} onClick={()=>report(true)}><Mail className="w-4 h-4"/>Send report</button></div></div>
  <div className="card p-4 grid gap-3 lg:grid-cols-4"><select className="input" value={client} onChange={e=>{setClient(e.target.value);setProject('');setCampaign('');setRecipient(clients.find(c=>c.id===e.target.value)?.email||'')}}><option value="">Select client</option>{clients.map(c=><option key={c.id} value={c.id}>{c.company_name}</option>)}</select><select className="input" value={project} onChange={e=>setProject(e.target.value)}><option value="">All client projects</option>{clientProjects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select className="input" value={preset} onChange={e=>setRange(e.target.value)}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="month">This month</option><option value="previous">Previous month</option><option value="custom">Custom dates</option></select><select className="input" value={timezone} onChange={e=>setTimezone(e.target.value)}><option>Asia/Dubai</option><option>UTC</option><option>Europe/London</option><option>America/New_York</option><option>Asia/Riyadh</option><option>Asia/Kolkata</option></select>{preset==='custom'&&<><input className="input" type="date" value={start} onChange={e=>setStart(e.target.value)}/><input className="input" type="date" value={end} min={start} onChange={e=>setEnd(e.target.value)}/></>}<select className="input" value={provider} onChange={e=>{setProvider(e.target.value);setCampaign('')}}><option value="">All platforms</option>{platforms.map(p=><option key={p.value} value={p.value}>{p.label}</option>)}</select><select className="input" value={campaign} onChange={e=>setCampaign(e.target.value)}><option value="">All campaigns</option>{(data?.campaigns??[]).map((c:any)=><option key={`${c.provider}-${c.id}`} value={c.id}>{c.name}</option>)}</select></div>
  <div className="flex gap-1 border-b border-sand-300 overflow-x-auto">{[['overview','Overview'],['campaigns','Campaigns'],['creatives','Ads & creatives'],['studio','Report builder'],...(canManage?[['connections','Connections']]:[])].map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`px-4 py-3 text-sm whitespace-nowrap border-b-2 ${tab===id?'border-brand-600 text-brand-700':'border-transparent text-taupe-500'}`}>{label}</button>)}</div>
  {loading?<div className="card p-12 text-center text-taupe-500">Building detailed report…</div>:<>
   {tab==='overview'&&<><div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{metrics.map(([label,value,key])=><div className="card p-4" key={key}><p className="text-xs uppercase tracking-wide text-taupe-500">{label}</p><p className="text-xl font-semibold mt-1">{value}</p><Delta value={changes[key]}/></div>)}</div><div className="grid lg:grid-cols-3 gap-4"><div className="card p-5 lg:col-span-2"><div className="flex justify-between"><h2 className="font-semibold">Daily media spend</h2><span className="text-xs text-taupe-500">{start} — {end}</span></div><Trend days={data?.days??[]}/></div><div className="card p-5"><h2 className="font-semibold">Efficiency</h2><div className="grid grid-cols-2 gap-y-4 mt-5 text-sm"><span className="text-taupe-500">CPM</span><b>{money(totals.cpm)}</b><span className="text-taupe-500">CPC</span><b>{money(totals.cpc)}</b><span className="text-taupe-500">Conv. rate</span><b>{pct(totals.conversionRate)}</b><span className="text-taupe-500">Engagements</span><b>{number(totals.engagements)}</b><span className="text-taupe-500">Video views</span><b>{number(totals.video_views)}</b></div></div></div><div className="grid md:grid-cols-3 gap-4">{platforms.map(p=>{const x=data?.byProvider?.find((v:any)=>v.provider===p.value)??{};return <div className="card p-5" key={p.value} style={{borderTop:`3px solid ${p.colour}`}}><h2 className="font-semibold">{p.label}</h2><div className="grid grid-cols-2 gap-3 mt-4 text-sm"><span className="text-taupe-500">Spend</span><b>{money(x.spend)}</b><span className="text-taupe-500">Impressions</span><b>{number(x.impressions)}</b><span className="text-taupe-500">CTR</span><b>{pct(x.ctr)}</b><span className="text-taupe-500">Conversions</span><b>{number(x.conversions)}</b></div></div>})}</div></>}
   {tab==='campaigns'&&<div className="card overflow-x-auto"><table className="w-full text-sm min-w-[1050px]"><thead><tr className="border-b border-sand-300 text-left text-taupe-500"><th className="p-4">Campaign</th><th>Platform</th><th>Spend</th><th>Impressions</th><th>Clicks</th><th>CTR</th><th>CPC</th><th>Conversions</th><th>CPA</th><th>ROAS</th></tr></thead><tbody>{(data?.campaigns??[]).map((c:any)=><tr className="border-b border-sand-200" key={`${c.provider}-${c.id}`}><td className="p-4 font-medium">{c.name}</td><td>{platforms.find(p=>p.value===c.provider)?.label}</td><td>{money(c.spend)}</td><td>{number(c.impressions)}</td><td>{number(c.clicks)}</td><td>{pct(c.ctr)}</td><td>{money(c.cpc)}</td><td>{number(c.conversions)}</td><td>{money(c.cpa)}</td><td>{c.roas.toFixed(2)}×</td></tr>)}</tbody></table></div>}
   {tab==='creatives'&&<div className="card overflow-x-auto"><table className="w-full text-sm min-w-[1100px]"><thead><tr className="border-b border-sand-300 text-left text-taupe-500"><th className="p-4">Ad / creative</th><th>Ad group</th><th>Campaign</th><th>Spend</th><th>Impressions</th><th>Clicks</th><th>CTR</th><th>Conversions</th><th>CPA</th><th>Status</th></tr></thead><tbody>{(data?.creatives??[]).map((a:any)=><tr className="border-b border-sand-200" key={`${a.provider}-${a.id}`}><td className="p-4"><b>{a.name||`Ad ${a.id}`}</b><div className="text-xs text-taupe-500">{a.type}</div></td><td>{a.adGroup}</td><td>{a.campaign}</td><td>{money(a.spend)}</td><td>{number(a.impressions)}</td><td>{number(a.clicks)}</td><td>{pct(a.ctr)}</td><td>{number(a.conversions)}</td><td>{money(a.cpa)}</td><td>{a.status}</td></tr>)}</tbody></table>{!data?.creatives?.length&&<div className="p-10 text-center text-taupe-500"><FileText className="w-8 h-8 mx-auto mb-3"/><p>Run the connection sync after the reporting-studio migration to import ad and creative detail.</p></div>}</div>}
   {tab==='studio'&&<div className="grid lg:grid-cols-3 gap-5"><div className="card p-5 lg:col-span-2"><h2 className="font-semibold text-lg">Executive commentary</h2><p className="text-sm text-taupe-500 mt-1">Add context, explain results, and state the next actions. This appears in the PDF.</p><textarea className="input min-h-56 mt-4" value={commentary} onChange={e=>setCommentary(e.target.value)} placeholder="Example: This month, search campaigns produced… Our recommendation for the next period is…"/></div><div className="card p-5 space-y-5"><div><h2 className="font-semibold">Voice annotation</h2><p className="text-sm text-taupe-500 mt-1">Attach a personal audio briefing to the client email.</p></div>{recording?<button className="btn-primary w-full flex justify-center items-center gap-2" onClick={stopVoice}><Square className="w-4 h-4"/>Stop recording</button>:<button className="btn-secondary w-full flex justify-center items-center gap-2" onClick={startVoice}><Mic className="w-4 h-4"/>{audio?'Record again':'Record voice note'}</button>}{audio&&<><audio controls className="w-full" src={URL.createObjectURL(audio)}/><button className="text-sm text-red-600" onClick={()=>setAudio(null)}>Remove voice note</button></>}<div><label className="text-xs uppercase text-taupe-500">Send to</label><input type="email" className="input mt-1" value={recipient} onChange={e=>setRecipient(e.target.value)} placeholder="client@example.com"/></div><button className="btn-primary w-full flex justify-center items-center gap-2" disabled={generating||!recipient} onClick={()=>report(true)}><Mail className="w-4 h-4"/>Generate & send</button><button className="btn-secondary w-full flex justify-center items-center gap-2" disabled={generating} onClick={()=>report(false)}><Download className="w-4 h-4"/>Save PDF only</button></div></div>}
   {tab==='connections'&&canManage&&<div className="card p-5"><h2 className="text-lg font-semibold">Platform connections</h2><p className="text-sm text-taupe-500 mt-1">Each connection belongs to the selected client and optional project.</p><form onSubmit={connect} className="grid md:grid-cols-5 gap-3 mt-4"><select className="input" value={form.provider} onChange={e=>setForm({...form,provider:e.target.value})}>{platforms.map(p=><option key={p.value} value={p.value}>{p.label}</option>)}</select><input required className="input" placeholder="Account ID" value={form.account} onChange={e=>setForm({...form,account:e.target.value})}/><input className="input" placeholder="Account name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/>{form.provider==='google_ads'&&<input className="input" placeholder="Manager account ID" value={form.manager} onChange={e=>setForm({...form,manager:e.target.value})}/>}<button disabled={!client} className="btn-primary flex justify-center items-center gap-2"><Link2 className="w-4 h-4"/>Connect</button></form><div className="space-y-2 mt-5">{connections.filter(c=>c.client_id===client).map(c=><div className="flex flex-wrap gap-3 items-center border border-sand-300 rounded-lg p-3" key={c.id}><b>{platforms.find(p=>p.value===c.provider)?.label}</b><span className="text-sm">{c.account_name||c.external_account_id}</span><span className={`text-xs px-2 py-1 rounded-full ${c.status==='active'?'bg-green-100 text-green-700':'bg-amber-100 text-amber-700'}`}>{c.status}</span><span className="text-xs text-taupe-500 flex-1">{c.last_synced_at?`Synced ${new Date(c.last_synced_at).toLocaleString()}`:'Not synced yet'}</span><button onClick={()=>sync(c.id)} title="Sync"><RefreshCw className="w-4 h-4"/></button><button onClick={()=>remove(c.id)} title="Remove"><Trash2 className="w-4 h-4 text-red-600"/></button></div>)}</div></div>}
  </>}</div>
}
